export interface GameFixture {
  id: string;
  seasonId: string;
  date: string; // ISO date
  status: 'SCHEDULED' | 'FINAL' | 'POSTPONED';
  gameType: 'REGULAR_SEASON' | 'PLAYOFFS';
  homeTeamId: string;
  awayTeamId: string;
  homeScore: number;
  awayScore: number;
  overtimePeriods: number;
}

/**
 * A full single round-robin among the six mock teams (15 completed games),
 * so every team plays every other team exactly once. All games are final —
 * Phase 1 only deals with completed box scores (see AGENTS.md: no live game
 * tracking).
 */
export const gameFixtures: GameFixture[] = [
  {
    id: 'game-001',
    seasonId: 'season-2025-26',
    date: '2025-11-01',
    status: 'FINAL',
    gameType: 'REGULAR_SEASON',
    homeTeamId: 'team-cascade',
    awayTeamId: 'team-meridian',
    homeScore: 108,
    awayScore: 101,
    overtimePeriods: 0,
  },
  {
    id: 'game-002',
    seasonId: 'season-2025-26',
    date: '2025-11-04',
    status: 'FINAL',
    gameType: 'REGULAR_SEASON',
    homeTeamId: 'team-sable',
    awayTeamId: 'team-cascade',
    homeScore: 97,
    awayScore: 102,
    overtimePeriods: 0,
  },
  {
    id: 'game-003',
    seasonId: 'season-2025-26',
    date: '2025-11-07',
    status: 'FINAL',
    gameType: 'REGULAR_SEASON',
    homeTeamId: 'team-cascade',
    awayTeamId: 'team-harborview',
    homeScore: 115,
    awayScore: 110,
    overtimePeriods: 0,
  },
  {
    id: 'game-004',
    seasonId: 'season-2025-26',
    date: '2025-11-10',
    status: 'FINAL',
    gameType: 'REGULAR_SEASON',
    homeTeamId: 'team-redstone',
    awayTeamId: 'team-cascade',
    homeScore: 104,
    awayScore: 99,
    overtimePeriods: 0,
  },
  {
    id: 'game-005',
    seasonId: 'season-2025-26',
    date: '2025-11-13',
    status: 'FINAL',
    gameType: 'REGULAR_SEASON',
    homeTeamId: 'team-cascade',
    awayTeamId: 'team-lakeshore',
    homeScore: 111,
    awayScore: 106,
    overtimePeriods: 0,
  },
  {
    id: 'game-006',
    seasonId: 'season-2025-26',
    date: '2025-11-16',
    status: 'FINAL',
    gameType: 'REGULAR_SEASON',
    homeTeamId: 'team-meridian',
    awayTeamId: 'team-sable',
    homeScore: 120,
    awayScore: 118,
    overtimePeriods: 1,
  },
  {
    id: 'game-007',
    seasonId: 'season-2025-26',
    date: '2025-11-19',
    status: 'FINAL',
    gameType: 'REGULAR_SEASON',
    homeTeamId: 'team-harborview',
    awayTeamId: 'team-meridian',
    homeScore: 96,
    awayScore: 89,
    overtimePeriods: 0,
  },
  {
    id: 'game-008',
    seasonId: 'season-2025-26',
    date: '2025-11-22',
    status: 'FINAL',
    gameType: 'REGULAR_SEASON',
    homeTeamId: 'team-meridian',
    awayTeamId: 'team-redstone',
    homeScore: 103,
    awayScore: 100,
    overtimePeriods: 0,
  },
  {
    id: 'game-009',
    seasonId: 'season-2025-26',
    date: '2025-11-25',
    status: 'FINAL',
    gameType: 'REGULAR_SEASON',
    homeTeamId: 'team-lakeshore',
    awayTeamId: 'team-meridian',
    homeScore: 109,
    awayScore: 104,
    overtimePeriods: 0,
  },
  {
    id: 'game-010',
    seasonId: 'season-2025-26',
    date: '2025-11-28',
    status: 'FINAL',
    gameType: 'REGULAR_SEASON',
    homeTeamId: 'team-sable',
    awayTeamId: 'team-harborview',
    homeScore: 112,
    awayScore: 107,
    overtimePeriods: 0,
  },
  {
    id: 'game-011',
    seasonId: 'season-2025-26',
    date: '2025-12-01',
    status: 'FINAL',
    gameType: 'REGULAR_SEASON',
    homeTeamId: 'team-redstone',
    awayTeamId: 'team-sable',
    homeScore: 98,
    awayScore: 95,
    overtimePeriods: 0,
  },
  {
    id: 'game-012',
    seasonId: 'season-2025-26',
    date: '2025-12-04',
    status: 'FINAL',
    gameType: 'REGULAR_SEASON',
    homeTeamId: 'team-sable',
    awayTeamId: 'team-lakeshore',
    homeScore: 121,
    awayScore: 115,
    overtimePeriods: 0,
  },
  {
    id: 'game-013',
    seasonId: 'season-2025-26',
    date: '2025-12-07',
    status: 'FINAL',
    gameType: 'REGULAR_SEASON',
    homeTeamId: 'team-harborview',
    awayTeamId: 'team-redstone',
    homeScore: 101,
    awayScore: 97,
    overtimePeriods: 0,
  },
  {
    id: 'game-014',
    seasonId: 'season-2025-26',
    date: '2025-12-10',
    status: 'FINAL',
    gameType: 'REGULAR_SEASON',
    homeTeamId: 'team-lakeshore',
    awayTeamId: 'team-harborview',
    homeScore: 106,
    awayScore: 102,
    overtimePeriods: 0,
  },
  {
    id: 'game-015',
    seasonId: 'season-2025-26',
    date: '2025-12-13',
    status: 'FINAL',
    gameType: 'REGULAR_SEASON',
    homeTeamId: 'team-redstone',
    awayTeamId: 'team-lakeshore',
    homeScore: 113,
    awayScore: 108,
    overtimePeriods: 0,
  },
];
